### ISSUE TITLE
原書に関する情報があったほうが初見の人にも親切だと思います

### ISSUE THREAD

**Issue by tenpoku1000** [ksuenaga/winskel-textbook-jp#3]
現状だと、出版社の書籍案内ページにある原書名を Web 検索する必要があると思いますが、
原書の案内ページへのリンクを載せておくと、親切だと思います。

**Comment by ksuenaga** [comment]
ありがとうございます．すぐ追記します．

**Comment by ksuenaga** [comment]
Addressed by PR #4.  Thanks!
