### ISSUE TITLE
正誤表の誤植と思われる箇所

### ISSUE THREAD

**Issue by kkinugasa** [ksuenaga/winskel-textbook-jp#32]
正誤表を作成いただき，ありがとうございます．
正誤表の中に誤植と思われる箇所があるため，ご報告致します．

https://github.com/ksuenaga/winskel-textbook-jp/blob/7f130a3a6fb7528d302db79311d9811bf02d495e/correction/correction.tex#L995

型は $\tau$ なので，

```tex
\item P.205, 型付け規則$\mathit{rec}$: 結論部分の「$\rec{y.(\lambda x.t)}$」は「$\rec{y.(\lambda x.t)}\new{ \COL \tau}$」の誤りです．
```

が適切であると思います．また，

https://github.com/ksuenaga/winskel-textbook-jp/blob/7f130a3a6fb7528d302db79311d9811bf02d495e/correction/correction.tex#L1107

は)が1つ多いので，

```tex
&\iff& \FunCmd{G;C}(\Encode{c}) \converge\\
```

が適切であると思います．

**Comment by ksuenaga** [comment]
Thanks!
