### ISSUE TITLE
5.3 二つの意味論の等価性 p.73

### ISSUE THREAD

**Issue by ruicc** [ksuenaga/winskel-textbook-jp#39]
> $a \equiv X$: 同様にして，もし $a$ がプログラム変数 $X$ ならば、
> $$(\sigma, n) \in \mathcal{A}\textlbrackdbl m \textrbrackdbl \Longleftrightarrow ...$$

とありますが、この $m$ は $X$ の間違いではないでしょうか。

**Comment by ksuenaga** [comment]
ありがとうございます．早めにチェックします．（ちょっといろいろ立て込んでいるので，少々お待ち下さい．）
