### ISSUE TITLE
「正誤表」リンク切れ

### ISSUE THREAD

**Issue by yutaro-sakamoto** [ksuenaga/winskel-textbook-jp#42]
[Webページ](https://ksuenaga.github.io/winskel-textbook-jp/)の「正誤表」がリンク切れになっており、404エラーコードを返します。
![image](https://github.com/ksuenaga/winskel-textbook-jp/assets/80912876/c18cb61e-4b30-41ae-8e62-865aea84fbb1)

**Comment by ksuenaga** [comment]
ありがとうございます！修正しました．
